/* Generated by scripts/generate_translations.js. */
(function (global) {
  'use strict';
  global.COURT_FORGE_TRANSLATIONS = Object.freeze({ en: Object.freeze({}) });
})(typeof window !== 'undefined' ? window : globalThis);
