const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
const schema=require(path.join(root,'js/data/player_attribute_schema.js'));
const failures=[];
if(schema.version!==3) failures.push(`schema version ${schema.version}`);
if(!schema.fields||schema.fields.HAN.label!=='控球') failures.push('HAN label must be 控球');
if(schema.fields.HAN.nba2kAttribute!=='Ball Handle'||schema.fields.HAN.excludedNba2kAttribute!=='Hands') failures.push('HAN semantics invalid');
if(!schema.calibration||schema.calibration.ovrUsedForAttributeFitting!==false||schema.calibration.uniformShiftForbidden!==true) failures.push('V9 calibration contract missing');
const child=cp.spawnSync(process.execPath,[path.join(__dirname,'validate_player_semantic_calibration_v9.js')],{cwd:root,encoding:'utf8'});
if(child.status!==0) failures.push(`semantic calibration failed: ${child.stdout||child.stderr}`);
console.log(JSON.stringify({schemaVersion:schema.version,HAN:schema.fields.HAN,semanticValidator:child.status===0?'PASS':'FAIL',failures},null,2));
if(failures.length) process.exitCode=1;
